### ISSUE TITLE
Which license do you apply for this repository?

### ISSUE THREAD

**Issue by Tiryoh** [frozenpandaman/splatnet2statink#10]
Dear @frozenpandaman ,

Thank you for your great work!
I love this software.

I would like to contribute to this repository, so could you apply a license for this repository?
https://help.github.com/articles/licensing-a-repository/

**Comment by Tiryoh** [comment]
I think 

* MIT license
* BSD license
* Apache license

are simple and great for this repository.

**Comment by frozenpandaman** [comment]
@Tiryoh, thanks! I had thought about it some but haven't applied one yet. I'll look into it tonight, in a few hours, and get back to you. (MIT is simple and permissive, which I think is good. GPL is enticing as well though since I would like others to open-source any projects based on this. And I'll have to read more about exactly what BSD and Apache entail.)

**Comment by frozenpandaman** [comment]
Added the GPLv3 license in 8923eec. :) Please feel free to reach out if you have any feedback, further questions, etc.!

**Comment by Tiryoh** [comment]
Thanks! ;)
