### ISSUE TITLE
Not generating cookie & not working with old saved one

### ISSUE THREAD

**Issue by allycatty** [frozenpandaman/splatnet2statink#102]
Tried with multiple accounts same issue across all. 

`Wrote session_token to config.txt.`
`Attempting to generate new cookie...`
`ally@veemo:~/veemo/splatnet2statink$ python splatnet2statink.py`
`splatnet2statink v1.5.4`
`Pulling data from online...`
`Blank cookie.`
`Attempting to generate new cookie...`
`ally@veemo:~/veemo/splatnet2statink`

**Comment by frozenpandaman** [comment]
Hm, I can't seem to replicate this:
```
eli:splatnet2statink eli$ ./splatnet2statink.py 
splatnet2statink v1.5.4
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Wrote iksm_session cookie for eli to config.txt.
Pulling data from online...
Number of recent battles to upload (0-50)? 
```

Is this still happening? Have you tried deleting your `config.txt` and trying from scratch (not just clearing `cookie` from it as your output suggests)?

**Comment by allycatty** [comment]
Hey Eli!
Yeah I have a little vps that runs checks for a few of my not so tech savvy
friends. I tried all of their config files, as well attempting to generate
a new one for my self from scratch. Just like in the output I posted in the
github, it doesn't even return an error just goes right back to the
console. Is there a a version of the python script that has a debug mode? I
could send you the output from that if it'd help!
Thanks for all the work you've put into this project!
-Ally

**Comment by frozenpandaman** [comment]
Hm, I really have no clue, but I would guess it's dependent on the setup of your VPS/server. Does it work if you try running it locally? I would think it'd _always_ return some sort of error – whether caught/handled by the script or maybe accidentally not – but not just pass silently. There's no special debug mode, just editing the file and manually adding in print statements really (again all of which should already happen in the script depending on where it runs into a problem…) I think your best bet would be for you to try doing this yourself at various points in iksm.py's `get_cookie()` and seeing where it stops, e.g. if a print is successful after the first nintendo.com request, then if the request to the s2s API succeeds, then if that to the flapg domain succeeds, etc. and just see if you can do a bit of debugging yourself since the problem at this point, I think, seems to be specific to your specific VPS setup.

One final guess is that I have manually blocked some IPs which were repeatedly spamming my site (_cough cough https://github.com/frozenpandaman/splatnet2statink/issues/98#issuecomment-620184506_) at a domain level, and if your script was set up to auto-run like that I may have done that to yours. I'd still think it'd give an error in that case, or really any case, though… but if you want to email or DM me on Twitter your VPS's IP I can double-check that.

**Comment by allycatty** [comment]
Yeah running it locally work so I have no doubt the ip probs got blocked. I'm so sorry for banging on your server too much and also not thinking to try running it locally first... I'd say I'd a python noob but that statement would be... generous....  The vps checks for 6 people with the default time for the -M flag but even with each person only checking every 5 min I'm sure a lot overlapped and it looked like it was just asking for a new cookie every minute or so because the scripts didn't start at the same time. Closing the issue and again... I'm so sorry. 😭
