### ISSUE TITLE
Need more info about self.

### ISSUE THREAD

**Issue by DaYu525** [frozenpandaman/splatnet2statink#116]
Hello, I find a telegram bot [Sp2battlebot](https://github.com/JoneWang/sp2battlebot). It can get my info more detailed. I want it can dispaly in stat.ink too. So could you please add this api.

![1021615622547_.pic_hd](https://tva1.sinaimg.cn/large/008eGmZEly1goic75fqwlj30o40k6gxx.jpg)

**Comment by frozenpandaman** [comment]
Hi,

I'm not familiar with this project or exactly what you're asking. I don't think stat.ink supports displaying things like bronze/silver/gold medals based on league placements – if you want that (or other stat.ink website features) to be supported, you'll need to ask @fetus-hina over at https://github.com/fetus-hina/stat.ink.

Thanks for bringing this project to my attention, though. It is masquerading as my app (uses the splatnet2statink user agent rather than a unique one), and violates the s2s API terms/usage guidelines in a number of other ways. It also uses my code without credit and applying the same license. I have reached out to the developer.
