### ISSUE TITLE
Error from the flapg API: Error 404 (offline or incorrect headers).

### ISSUE THREAD

**Issue by luiscarlospando** [frozenpandaman/splatnet2statink#138]
```
Wrote session_token to config.txt.
Attempting to generate new cookie...
Error from the flapg API: Error 404 (offline or incorrect headers).
```

Any clue about what's happening?

Thanks!

**Comment by guigas7** [comment]
same here
![image](https://user-images.githubusercontent.com/11247506/167964257-d3af9df1-0007-45ea-a8e9-720c73154cd2.png)

it's been going on for a few days

**Comment by frozenpandaman** [comment]
Will look into it (by which I mean I asked NexusMine, lol).

We might be able start running this API ourselves, in preparation for supporting Splatoon 3, if @clovervidia is up for the challenge. Here's the JS code, which uses Frida, that we'd have to port over:
https://github.com/samuelthomas2774/nxapi/commit/2005f34780b9209d0c4568a508638ae8d55aec76

Here were some other folks on Reddit willing to help (I've just yet to coordinate everything, but this summer seems like a good time for it):
 - [/u/samuelthomas2774 via this comment](https://old.reddit.com/r/NintendoSwitch/comments/tpzabb/introducing_nsorpc_an_app_that_shows_what_switch/i2kk9ny/)
 - [/u/Mi460 via DMs](https://www.reddit.com/r/NintendoSwitch/comments/tpzabb/introducing_nsorpc_an_app_that_shows_what_switch/)

**Comment by frozenpandaman** [comment]
Will look into it (by which I mean I asked NexusMine, lol).

We might be able start running this API ourselves, in preparation for supporting Splatoon 3, if @clovervidia is up for the challenge. Here's the JS code, which uses Frida, that we'd have to port over:
https://github.com/samuelthomas2774/nxapi/commit/2005f34780b9209d0c4568a508638ae8d55aec76

Here were some other folks willing to help (I've just yet to coordinate everything… or even reply to people, have been busy due to school, but this summer seems like a good time for it):
 - @samuelthomas2774 / [via this comment](https://old.reddit.com/r/NintendoSwitch/comments/tpzabb/introducing_nsorpc_an_app_that_shows_what_switch/i2kk9ny/)
 - @MCMi460 / [via DMs](https://www.reddit.com/r/NintendoSwitch/comments/tpzabb/introducing_nsorpc_an_app_that_shows_what_switch/)

**Comment by JoneWang** [comment]
It is also possible to use the [imink api](https://github.com/JoneWang/imink/wiki/imink-API-Documentation). imink api is free and accessible for free. And it has a [status page](https://status.imink.app) for monitoring availability.

**Comment by frozenpandaman** [comment]
@luiscarlospando @guigas7 Seems to be working now.

@JoneWang Thanks a ton! Ideally, in the near future (in preparation for Splatoon 3 stuff), I'd like get this up & running & integrated into the s2s API again – so the script doesn't need to make requests to all these various other servers. (And then if something does go wrong or mess up, we can fix it on our end instead of waiting for third-party devs or whatever other services.) How are you running the Android server behind the imink API, i.e. what's the technology behind this all? I posted a way using [Frida](https://frida.re/) above which I've yet to look into. Is what you're doing similar? If you'd be willing to help out here it'd be pretty awesome – feel free to DM me on Twitter or Discord as well.

P.S. Impressive status dashboard!

**Comment by JoneWang** [comment]
I did not use Frida. My implementation would probably be simpler and maintenance free. 
I will send you a message in Twitter.

**Comment by frozenpandaman** [comment]
@JoneWang Just want to say sorry for the late reply here, have been busy and preparing for some upcoming travel – but I got your Twitter DM and will reply shortly! 🙏
