### ISSUE TITLE
splatnet2statink on android

### ISSUE THREAD

**Issue by OctoFloofy** [frozenpandaman/splatnet2statink#145]
Hello, i got the program to work on Android! It just behaves like it would on PC. Would you be interested in installation instructions?

**Comment by frozenpandaman** [comment]
@OctoFloofy Sure, I'd definitely be interested in learning more about your setup! Sounds interesting, thanks!

**Comment by OctoFloofy** [comment]
Its actually pretty easy, unfortunately i did the setup yesterday and dont remember the exact steps and commands anymore but it progresses easily anyways. 

First you want to install Termux: https://f-droid.org/packages/com.termux/
Don't install the Play Store version as its outdated.
Then you install git within termux with the following command: `pkg install git`
Also install python with `pkg install python`
After that clone your repo with the command listed in in your setup instructions.
Everything from here on can use the usual provided setup instructions of the repo. 

To run the script navigate to the program folder with `cd splatnet2statink`
Use any of the example commands provided in the repo to execute.

**Comment by frozenpandaman** [comment]
Yup, that makes sense & was pretty much all I was wondering. :) splatnet2statink should run on the command line with any shell on any operating system – so this includes terminal emulators on Android. I'm guessing that most people who want to do this can figure out how to access the command line on their phones instead of computer, but maybe it's worth explicitly calling out for s3s.

Thanks!
