### ISSUE TITLE
9403 - Invalid Token

### ISSUE THREAD

**Issue by BlueLappy** [frozenpandaman/splatnet2statink#152]
Hello I was trying to upload matches to stat ink and keep running into this error
![github](https://github.com/user-attachments/assets/18478f15-6525-4b90-a1f8-f8257c6c7edd)

Not sure if this is on my end or not as I use the same account for s3s and that works just fine, thanks in advance!

**Comment by frozenpandaman** [comment]
Hi @BlueLappy! Thanks for following up on your email via GitHub :)

It seems that some people's old cookies were still working, and battles were still occasionally being uploaded to stat.ink (I asked Hina to confirm… even if not many, as Splatoon 2 is not played much anymore 😅) but like you, I couldn't generate a new cookie from scratch. This is because the f API was assuming we were using the most recent app version, 2.11.0, which _does not work_ at the moment… luckily, 2.10.1 still works, so now I've changed to fetch that version from the API itself (which is now something it provides… didn't at the time s2s was written!) & use that that.

I'd delete your config.txt and start from scratch, and it should be good now! Thanks!

**Comment by BlueLappy** [comment]
It works! Thank you!
