### ISSUE TITLE
"Invalid token." error from Nintendo

### ISSUE THREAD

**Issue by mkody** [frozenpandaman/splatnet2statink#18]
I can't use the script anymore and get this error:

```
Wrote session_token to config.txt.
Error from Nintendo:
{
  "status": 9403,
  "errorMessage": "Invalid token.",
  "correlationId": "9a1ee46a-d7e527d1"
}
```

I tried to delete my `config.txt` and re-login, tried to logout from the browser then login first on mobile and then again from the browser, still getting this error.

**Comment by mkody** [comment]
I haven't played since last Splatfest, so dunno when it could have gone wrong.
Currently on d19c158

**Comment by frozenpandaman** [comment]
Hi @mkody,

Yup, this is a known issue that was unfortunately introduced in the latest app update, and affects _all_ scripts/programs/websites interfacing with information from SplatNet 2. Please see the readme:

>UPDATE: The authentication process has changed in the 1.1.0 update to the Nintendo Switch Online app. Existing, non-expired cookies can still be used to run the script and access the site, but trying to generate a new cookie will now produce the message "Invalid token." We're working on a fix ASAP. For now, follow the mitmproxy instructions [here](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions).

The problem is that `session_token`s cannot be used to generate `iksm_session` cookies anymore without sending another parameter alongside it – and this parameter is only able to be generated in the app. So, you'll need to intercept the traffic from your phone by using mitmproxy (or something similar) to get a valid cookie, and then just put that in `config.txt` for the script to use.

**Comment by mkody** [comment]
Oh welp, didn't see that (it's far in the bottom of the readme, tho). Thanks!

**Comment by frozenpandaman** [comment]
Yeah, we (along with some others who are working on similar stuff) were hoping to find a solution or a way to generate the newly-introduced `f` token but not really having much luck. I'll talk with @clovervidia tomorrow about changing up the I/O since, by this point, the need for the mitm instructions (unfortunately) seems more than temporary.
