### ISSUE TITLE
Login with username & password

### ISSUE THREAD

**Issue by blackgear** [frozenpandaman/splatnet2statink#2]
Feel free to use my code: https://github.com/blackgear/NSOnline_Bot/blob/master/session_token.py

It shows how to get a vaild session_token with your username and password.

**Comment by clovervidia** [comment]
This is very much appreciated. I figured out how to generate the redirect_uri but got stuck on how to log in through the console given username and password because of the captcha response in the POST.

**Comment by blackgear** [comment]
In fact, you don't need to deal with the captcha, the _h parma is a hmac_sha256 of the request, you could see how it calculated in codes.

😄

**Comment by frozenpandaman** [comment]
Wow, thank you for this! We've been working to figure this out over the past few days (though I've been a bit busy myself and haven't really gotten a chance to do much in the way of that). @clovervidia figured out a lot of the internals, including generating the final `session_token` from `/connect/1.0.0/api/session_token`, given the `session_token_code` found in the `npf71b963c1b7b6d119://` protocol button on the `/connect/1.0.0/authorize`/account linking page. Logging in was proving a bit of the challenge, though!

A lot of this code is already incorporated/being done in `iksm.py`, which is used to generate the `iksm_session` cookie from the final `session_token`. If you wanted to send a PR just adding the file you linked to the repo, @blackgear, we could work to incorporate the login code. Otherwise, we'll just reference your linked file (and credit you at the top, of course) in a modified `iksm.py`, if that's alright with you.

**Comment by blackgear** [comment]
I'm just rewrite a login module that figure out all this staff. Maybe I can add the PR in two days.

Also I should point out this line: https://github.com/frozenpandaman/splatnet2statink/blob/master/splatnet2statink.py#L24

the `x-unique-id` is a token in fact. 

this unique-id is generated at: https://github.com/blackgear/NSOnline_Bot/blob/master/bot.py#L120

if you want to do more thing(order a gear at shop for example), you need a vaild unique id to do that.

**Comment by clovervidia** [comment]
I also noticed that ID was in the source when I accessed SplatNet 2 from my browser, and that it was different than frozenpandaman's, but neither of us could figure out what it was for.  We didn't intend for this tool to be used for anything other than running in the background to upload battles to stat.ink as they happened, but it would probably be best if we obtained the user's unique ID rather than using one of our own. Thanks for bringing it up.
And I'm planning to finish adding your code to generate _h and the other things necessary to log in to the account to iksm.py and integrating it probably today or tomorrow, but if you'd like to make a PR to improve or add to it, you're more than welcome to.

**Comment by blackgear** [comment]
Now renamed my project to [NSOnline_API](https://github.com/blackgear/NSOnline_API)...

Just use the splatoon.get_results to pull the data.

NSOnline_API is a good wrapper that handles all login issues and network problems.

I think the PR should work but I had to go bed...

**Comment by frozenpandaman** [comment]
Since you opened a related PR, #3, I'll move the conversation there and close this. :)
