### ISSUE TITLE
Fetch weapons from https://stat.ink/api/v2/weapon ?

### ISSUE THREAD

**Issue by martinemde** [frozenpandaman/splatnet2statink#33]
Is it worth fetching the weapons and stages from the api to avoid the weekly updates that are required?

The obvious downside is that the api response is huge. It could be trimmed down to only the number and word with help from @fetus-hina.

**Comment by clovervidia** [comment]
I've considered it a few times, but I thought it might be making too many requests to stat.ink. Supposing we did hit the stat.ink endpoint to update the local database regularly, say every few days or so, do you think we should update the dbs.py file with the new weapons and stages, or do it some other way? I haven't worked with file manipulation much so I'm a little concerned about the other things we have in that file, like the numbers for profile picture colors and Splatfest ranks, things that stat.ink doesn't offer, being overwritten, or having to constantly be rewritten to the file following the new information.

It certainly would be convenient at any rate. We wouldn't have to update the version number for every new addition to the database unless we change how the database is accessed, and people who don't update their copy of the script for whatever reason would also be able to have the latest database. I'd like to see it done through some manner.

**Comment by frozenpandaman** [comment]
Would it fetch every time the script runs, though? Or how would we control that, &c? The vast majority of the time someone runs the script there will be no new weapons/updates, and having an updating mechanism rely on an external site/database adds a sort of bulk to the project (at least conceptually, or for me). Also we usually update before stat.ink and it's nice to be able to update/control the code, and the code that users have, on our own schedule. 😝

I see how this could be a useful feature, though updates are really only scheduled to last for another half year at most and we've already come this far doing it this way. Plus, looking at [our 22 users from the last 24 hours](http://elifessler.com/s2s/2018-02-27_12.txt), 19 are on the latest version four days after the latest dbs.py update (between last Friday and now), so we don't really have an issue with adoption. That is, if it's even worth it to do something like this for 30-ish users on a regular basis. :P

I sort of think it's nice for us to control the releases and data/databases entirely on our end – both on our own schedule (usually a few minutes after announcement since I'm up late) and here, in a single location. And then it's on users to update their clients (simple using git or the built-in updater) which most seem to be diligent at doing.

Closing this issue for now, then, because I miss having that 0️⃣ next to the Issues tab (😛), but feel free to continue any discussion as well.

**Comment by martinemde** [comment]
That all makes sense. Thank you
