### ISSUE TITLE
Battle uploaded to None

### ISSUE THREAD

**Issue by martinemde** [frozenpandaman/splatnet2statink#48]
Hi @frozenpandaman, 

I'm trying to debug why I'm getting this message repeatedly after some of the newest updates. It hasn't worked right since around the python3 upgrade, but it was working fine with the initial branch you were testing.

I'm only having this error when it's running on my server, but I'm not sure how to debug it so I don't know how to tell what's different between the two environments.

**Comment by clovervidia** [comment]
Do the battles actually upload? I'd suggest printing the headers you get back from stat.ink and seeing if the field names changed, or if you're getting anything back at all.

**Comment by martinemde** [comment]
The battles don't get uploaded. I can reupload them later. I'll try that.

**Comment by clovervidia** [comment]
Very strange. If you are reaching stat.ink and getting an error message back, that should be handled and displayed, so it sounds like it might be a network issue. I think looking into the headers or pulling out some of the try/except statements to get some error messages would be a good place to start if you're unable to upload.

**Comment by martinemde** [comment]
``` Battle uploaded to None
2018-04-19T17:52:41.233425+00:00 app[scheduler.4414]: Headers: {'Server': 'h2o/2.2.4', 'www-authenticate': 'Bearer realm="api"', 'x-frame-options': 'SAMEORIGIN', 'x-ua-compatible': 'IE=Edge', 'cache-control': 'no-transform', 'content-type': 'application/json; charset=UTF-8', 'x-xss-protection': '1;mode=block', 'Date': 'Thu, 19 Apr 2018 17:52:41 GMT', 'public-key-pins': 'pin-sha256="utBo7ONcAC4aAWyTnk/mZoWtLlC0HSH3AGp23Jiygwg="; pin-sha256="1Wi/XQLwoaHjRxs3ddbVVjHO3VFTjHdYzRYa7ODBrbQ="; max-age=5184000; includeSubDomains', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'Connection': 'close', 'access-control-allow-origin': '*', 'x-powered-by': 'PHP/7.1.16', 'x-content-type-options': 'nosniff'}```

**Comment by clovervidia** [comment]
My mistake, I thought the URL information was in the headers. Try reading the text/content of the response.

**Comment by martinemde** [comment]
Seems like my api token was getting lost when the session token was used to refresh the cookie. I haven't made a great solution for the cookie generation yet because it requires some sort of persistent storage. I'm just making new tokens every hour right now.

**Comment by martinemde** [comment]
Here's the error that wasn't being displayed properly:

```json
{
  "name": "Unauthorized",
  "message": "Your request was made with invalid credentials.",
  "code": 0,
  "status": 401
}
```

**Comment by clovervidia** [comment]
Hmm, that's strange because that should be tripping the try/except that attempts to read `postbattle.headers.get('location')` which should go to the except and print the error message, but I'm not sure why that's not happening.

**Comment by martinemde** [comment]
Does `get` fail if the key doesn't exist?

**Comment by clovervidia** [comment]
I see. Then you're right, it wouldn't be able to catch that the way it's set up right now. It should probably attempt to read `message` from the text if one is available to see if there was a error. Or do you think we should use the status codes because it looks like you got a 401 when you did that?

**Comment by frozenpandaman** [comment]
Hm, yeah, the `except` block isn't ever being reached – which makes sense, I think, since we're using `.get()`. I'm able to replicate this by changing my stat.ink API key to something invalid (but still of the correct length):
```
Number of recent battles to upload (0-50)? 1
Battle #1 uploaded to None
```
I can achieve the same affect by changing the dbs.py dictionary value for a weapon that's present in a battle json. The key isn't recognized by stat.ink so it should give an error and spit it back out to us, but instead I'm getting that same success message.

…But I've definitely seen the "Error uploading battle #n. Message from server: ... Continue (y/n)?" error message before so I'm not sure what happened to make that seemingly unreachable now. This doesn't seem to be a Python 3-exclusive issue either (i.e. behaves the same even if using 2.7).

Anyway, trying out @clovervidia's changes on the handling-blank-api-keys-better branch seems to fix this (in both cases) and is a better way to go about doing it (since I'd personally only really expect exceptions when using the index/brackets operator) so I'll merge that into master.

**Comment by martinemde** [comment]
Looks good. Thank you @clovervidia @frozenpandaman
