### ISSUE TITLE
Splatfest experience calculation error

### ISSUE THREAD

**Issue by ticky** [frozenpandaman/splatnet2statink#52]
Hi there,

It looks like there might be an issue with the calculation of Splatfest experience. I got this error from stat.ink:

```
Error uploading battle. Message from server:
{
    "error": {
        "fest_exp": [
            "Fest Exp must be no less than 0."
        ]
    }
}
```

Getting some debug output, it’s from a battle with this JSON representation: 
https://gist.github.com/ticky/4979cdd367364e5e66ff7e71307a7e0f#file-fes-1529812235-from-nintendo-json. I’ve also attached the JSON splatnet2statink attempted to upload: 
https://gist.github.com/ticky/4979cdd367364e5e66ff7e71307a7e0f#file-fes-1529812235-uploaded-json

Which is producing a `fest_exp` output of `-1`, as of revision d236adc87d0b80b73e5a2f50ca6ea31fd6db1455 (current master), when it should be `0`.

**Comment by frozenpandaman** [comment]
Hah! OK, so the other team was *exactly* 1800 in estimate_fes_power, which should have caused the "win" (not "turf inked") portion of `points_gained` to be 5, but instead it was getting set to 6.

It was being calculated as follows:
```
payload["fest_exp"] = (fest_rank_rollover: 0) + (fest_exp_after: 7) - (points_gained: 2 + 6)
```

https://github.com/frozenpandaman/splatnet2statink/blob/d236adc87d0b80b73e5a2f50ca6ea31fd6db1455/splatnet2statink.py#L953-L956

As you can see by the comments (`# 1720 - 1780`, `# 1810 - 1890`), these values were all set from my anecdotal evidence but I hadn't seen/had a battle against a team with an average power of *exactly* 1800, so the value was off here. So in the first line/case in the snippet above, the `<` should be a `<=`, and (probably) vice versa for the second case. I'll do some more testing and fix this later tonight! Thanks for the heads up!

**Comment by ticky** [comment]
No problem at all! Glad you’ve got some idea of where it came from 😃

**Comment by frozenpandaman** [comment]
Actually, I think 1800 should give +6, or at least did for this past Splatfest…

Would you happen to have the JSON or stat.ink URL for the battle right before this one, @ticky?

**Comment by frozenpandaman** [comment]
OK, there's some damn weird stuff going on here… sometimes the points gained behave unexpectedly when changing titles.

---

\- The parenthetical (+2)s are for the player inking over 400p of turf, relevant for all the battles here.

\- Note that only the second number (after/on the right side of the "→") on stat.ink battle pages is 100% accurate, as only this number is provided in SplatNet JSONs; the first number is calculated by s2s, but sometimes this calculation is done incorrectly (and that's what I'm attempting to fix in this issue). The numbers below, however, are all accurate and obtained by clicking the "Prev. battle" battle button from each link and taking the second number from *that* page.

\- Fanboy/girl is out of 10 points, Fiend is out of 25, and Defender is out of 50. So, say, if a player started at Fangirl 5 and gained +7 points total from a win, they'd end up at "Fangirl 12" – aka next title (Fiend) 2.

---

* Winning against **1399 and below** (through at least 1200)…
  * …gives +3: https://stat.ink/@paulsama/spl2/562121 (10 → 15)
    * 10(+2) + 3 = 15
* —————————————————————————
* Winning against **exactly 1400**…
  * …gives +4: https://stat.ink/@kazuki_ashiya/spl2/413530 (2 → 8)
    * 2(+2) + 4 = 8
* —————————————————————————
* Winning against **1401–1699**…
  * …gives +4: https://stat.ink/@origotoh/spl2/797934 (9 → 15)
    * 9(+2) + 4 = 15
* —————————————————————————
* Winning against **exactly 1700**…
  * …sometimes gives +4: https://stat.ink/@beanslee/spl2/1022828 (21 → 27)
    * 21(+2) + 4 = 27
  *  …sometimes gives +5: https://stat.ink/@ticky/spl2/1040174 (Defender 48 → Champion 5)
    * 48(+2) + 5 = 55 aka next title 5
  *  …sometimes gives +5: https://stat.ink/@flukekie/spl2/1020317 (Fanboy 8 → Fiend 5)
    * 8(+2) + 4 = 15 aka next title 5
* —————————————————————————
* Winning against **1701–1799**…
  * …gives +5: https://stat.ink/@imc68uk/spl2/1027779  (10 → 17)
    * 10(+2) + 5 = 17
  * …gives +5: https://stat.ink/@alanaktion/spl2/1043203 (Defender 48 → Champion 5)
    * 48(+2) + 5 = 55 aka next title 5
* —————————————————————————
* Winning against **exactly 1800**…
  * …sometimes gives +6: https://stat.ink/@shiokonbu/spl2/1022230 (16 → 24)
    * 16(+2) + 6 = 24
  * …sometimes gives +6: https://stat.ink/@Benjamaster/spl2/1032175 (4 → 12)
    * 4(+2) + 6 = 12
  * …sometimes gives +5: https://stat.ink/@obatyan789/spl2/1028024 (Fiend 20 → Defender 2)
    * 20(+2) + 5 = 27 aka next title 2
* —————————————————————————
* Winning against **1801–1899**…
  * …gives +6: https://stat.ink/@gungun974/spl2/1029889 (60 → 68)
    * 60(+2) + 6 = 68
  * …gives +6: https://stat.ink/@Benjamaster/spl2/1033385 (Fiend 20 → Defender 3)
    * 20(+2) + 6 = 28 aka next title 3
* —————————————————————————
* Winning against **exactly 1900**…
  * …gives +7: https://stat.ink/@into_the_trash/spl2/1020240 (3 → 12)
    * 3(+2) + 7 = 12
* —————————————————————————
* Winning against **1901 and above** (through at least 2500)…
  * …gives +7: https://stat.ink/@mak4026/spl2/745451 (20 → 29)
    * 20(+2) + 7 = 29

---

So, when does defeating a team with 1700 power give +4 and when does it give +5, and the same for 1800 and the usual +6 vs. +5? It seems there's special cases when you rank up in title… but also  *only* for when you beat a team with one of those exact, round powers…? This is so obscure and specific… crazy bizarre… is there something I'm totally missing or overlooking here? Any ideas?

**Comment by ticky** [comment]
> EDIT: Wait, was this by chance your very first battle in that Splatfest?

I believe it was, yeah.

> This is so obscure and specific… crazy bizarre… is there something I'm totally missing or overlooking here? Any ideas?

I’m really not sure, sorry!

**Comment by ticky** [comment]
Oh also, I actually ended up [uploading it to stat.ink](https://stat.ink/@ticky/spl2/1040334) by forcing that value to be at least zero. That was probably silly!

**Comment by frozenpandaman** [comment]
Alright, I've fixed it on my end so all the cases above work, at least… but yours is still weird. Why did you gain +7 from that battle? You got +2 for inking, and then apparently +5 for the win… but the only other "+5" cases I can find are when you change/rank up in title, which you didn't do.

**Comment by frozenpandaman** [comment]
More instances of +5 without title changes against exactly 1800 power:
* https://stat.ink/@flukekie/spl2/1022287 (87 → 94)
* https://stat.ink/@kgtkr/spl2/1025956 (55 → 62)
* https://stat.ink/@jet68668/spl2/1027543 (10 → 17)
* https://stat.ink/@nigaky/spl2/1027987 (26 → 33)
* https://stat.ink/@wata516/spl2/1028072 (66 → 73)
* https://stat.ink/@Benjamaster/spl2/1032175 (5 → 12)
* https://stat.ink/@Marolita/spl2/408495 (1 → 8)
* https://stat.ink/@collider/spl2/408663 (8 → 15)
* https://stat.ink/@TurboK/spl2/424813 (2 → 9)

I'll see if I can figure out a pattern/something about these that's making them be worth +5 instead of +6.

**Comment by frozenpandaman** [comment]
I reached out to @Leanny and he confirmed that the code Splatoon 2 uses to determine this +exp value *really is* as simple as it would seem (you can never be too sure with this game…):

```
if q >= 1900.0 return 7
if q >= 1800.0 return 6
if q >= 1700.0 return 5
if q <  1400.0 return 3
else           return 4
````
where `q` is the average MMR of the non-d/c'd enemy players.

The game (and SplatNet) *does* round this value, but that doesn't explain *all* of these evidently rule-breaking cases where winning against ≥1700 gives +4 instead of +5 – those can't all just be due to rounding, as that'd be a pretty rare occurrence for it to affect this to this degree. So something's still most probably going on, but I don't really know what (at all), and don't think it's feasible to discover, really.

Since this if/else block is the logic the game uses, we should mirror it, and then just catch fatal mess-ups (e.g. if `fest_exp` is calculated to be -1 for some stupid reason – which we are already doing now due to this issue, yay!) … and we can always continue to poke around non-fatal ones (where the previous battle's accurate `fest_exp_after` doesn't match the current battle's calculated `fest_exp`, just like is happening now) in case anything comes of that in the future. (Thanks to @fetus-hina for providing me with all the exactly-1700, 1800, etc. battle IDs as well which allowed me to look into this so in-depth.)

Maybe this next commit then will magically fix things going forward? Probably not, but if so, damn has this been overcomplicated… for some reason. And if these stats in some peoples' battles do continue to be ever-so-slightly off, well… too bad. :P

Fun investigating!
