### ISSUE TITLE
"server maintenance" error

### ISSUE THREAD

**Issue by rash67** [frozenpandaman/splatnet2statink#59]
I'm not sure if this is a forwarded error message from nintendo, but I setup my original cookie stat.ink API key, and try to update my stat.ink battles:

./splatnet2statink.py -r
splatnet2statink v1.2.1
Blank cookie.
Attempting to generate new cookie...
Error from the splatnet2statink API:
{
  "error": "Server maintenance"
}
This happened the first time when I pasted the URL to get a cookie as well. Is it the blank cookie message I should be tracing down? or the server maint?

I haven't been able to login via squidtracks either, it gets stuck in a loop of choosing login, sleect this person, "logging on..." then back to the "login / login with session cookie".

I tried the session cookie method to no avail as well.

let me know any info I can provide

thanks

**Comment by frozenpandaman** [comment]
Hey @rash67,

Nintendo changed the login method in the latest update to the app, and we still haven't figured out how to generate one of the parameters we need. As a result, 

In 1.2.1, I changed it so when a config.txt is generated, the word "skip" would be input as the session token and

**Comment by frozenpandaman** [comment]
Hey @rash67,

Nintendo changed the login method in the latest update to the app, and we still haven't figured out how to generate one of the parameters (`f`) we need – which is what the splatnet2statink API's purpose was. As a result, I took it offline until we have generation solved again, because I didn't see the point in returning broken/not working tokens to the user. I'm realizing I could have probably put a more informative message in there briefly explaining the situation instead of just saying there's "maintenance" (forgot anyone would see it!) so I'll go ahead and update that now. Thanks!

In v1.2.1 of the script, I changed it so when a config.txt is generated, the word "skip" would be automatically input as the session token which essentially tricks the script into thinking you want to input an `iksm_session` cookie manually – which is the only way to do it, for the time being (a bit janky, I know, but we're hoping this is a temporary thing at the very least). But of course you're an existing user with a session token already filled out, so…

What you'll want to do is just delete your config.txt (or change the `session_cookie` value in it to just say "skip" if that's easier for you) and then run the script again, and then follow the [mitmproxy instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) to input your cookie manually. I know SquidTracks has an option for this somewhere as well. I've changed it so the message returned by the API gives instructions along these lines now, too.

You said "I tried the session cookie method to no avail as well" – is this what you meant by that? If you can't figure out the mitmproxy instructions, just let me know here and I can try to help with that.

(The closing and opening thing was me being on mobile and accidentally pressing the button, sorry. 🙃)

**Comment by rash67** [comment]
i got the iksm direct to work by letting the script fill in the session id and getting the cookie with iphone + proxy to watch api calls the app makes

it looks like you might just change to start with the gameweb-something api call (watched the proxy when i got cookie)

i started to take a whack at iksm.py but am a bit busy

if i can help, lmk

Sam Rash
sam.rash@gmail.com

**Comment by frozenpandaman** [comment]
>i got the iksm direct to work by letting the script fill in the session id and getting the cookie with iphone + proxy

Session token doesn't really matter if you're inputting in a cookie by hand, since it's only used to *generate* those cookies (which we can't do anymore, for the time being). 

>the app makes it looks like you might just change to start with the gameweb-something api call […] i started to take a whack at iksm.py

Sorry, what do you mean? And what about iksm.py?

**Comment by frozenpandaman** [comment]
Closing because you said this was taken care of for you.
