### ISSUE TITLE
W1/W2 Failure does not include wave_details

### ISSUE THREAD

**Issue by emaame** [frozenpandaman/splatnet2statink#65]
I tested a new experimental brunch, salmon-run.
I found salmon_post_shift failed if **W1/W2 failure** has included in results.

> Traceback (most recent call last):
>   File "splatnet2statink.py", line 1259, in <module>
>     salmonrun.upload_salmon_run(A_VERSION, YOUR_COOKIE, API_KEY, app_head)
>   File "salmonrun.py", line 202, in upload_salmon_run
>     salmon_post_shift(i, results)
>   File "salmonrun.py", line 104, in salmon_post_shift
>     payload[wave_str]["water_level"] = results[i]["wave_details"][wave]["water_level"]["key"] # low, normal, high
> IndexError: list index out of range

I know it can fix by checking results[i]["wave_details"][wave] is available,
but I don't know how the data should process.

I'm so excited to collect data!

**Comment by frozenpandaman** [comment]
Thanks for the note! I'll fix this later today.

Note that the branch is still highly experimental, with features being added gradually, so crashes like this are probably to be expected going forward. The branch doesn't even currently upload anything to stat.ink – it just prints the payload that it *would* upload, i.e. details about the shifts (since stat.ink doesn't support uploading this info yet, and likely will change in implementation when it does.) As the stat.ink API begins to flesh out support for this and adds user-facing display for this info on the site, I'll update the branch and script accordingly.

**Comment by frozenpandaman** [comment]
hahaha i don't know how to use git have fun rebasing y'all
