### ISSUE TITLE
Can't rename proxy in iOS

### ISSUE THREAD

**Issue by gotmilk0112** [frozenpandaman/splatnet2statink#66]
Stuck on step 7 for iOS. It tells me to rename the proxy profile, but there is no option to rename it anywhere.

Nintendo Switch Online app just keeps saying the connection is unstable.

**Comment by frozenpandaman** [comment]
@clovervidia Can you help with this? I'm on vacation and not online much. Otherwise I'll look into this in a few days.

**Comment by clovervidia** [comment]
I'm not familiar with the procedure for iOS, and I don't see a step in our readme or on our mitmproxy wiki page about renaming the proxy profile. Can you link me to the steps you are following?

**Comment by gotmilk0112** [comment]
Huh, I think I'm in the wrong issues section......somehow.

This one, for SquidTracks:

https://github.com/hymm/squid-tracks/wiki/en_getCookie

Step 7 says to name the certificate, but I can't name it.

**Comment by clovervidia** [comment]
That would explain it. I'm surprised they're using their own proxy instead of using mitmproxy, but that's not important right now. Renaming the certificate shouldn't be necessary to making it work, that's just to make it easier for you to find and remove when you're done. If you're having difficulty getting that proxy to work, I would suggest following [our instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) for using mitmproxy, which will also allow you to get your `iksm_session` cookie.

**Comment by gotmilk0112** [comment]
I can't get that to work either. I got as far as getting into the mitmproxy tab and seeing the "cookie" bit, but it's a few letters followed by two long numbers with a period in between, and no matter what I try entering into Squidtracks, it just gives an error.

**Comment by clovervidia** [comment]
The cookie should be 40 characters long, so I'm not sure what happened the first time, but if you got it working, then that's all that matters. I'll close this issue since it seems to be resolved, and if you have further problems with the proxy, feel free to stop by again.
