### ISSUE TITLE
No error message when errored while generating cookie

### ISSUE THREAD

**Issue by SimonOrJ** [frozenpandaman/splatnet2statink#81]
Hello!

I cannot upload my data to stat.ink anymore.  The new cookie won't generate, and now there's no error to know why.

```
$ python splatnet2statink.py -t
splatnet2statink v1.4.3
Pulling data from online...
Blank cookie.
Attempting to generate new cookie...
$
```

Last time the error was that the API was outdated.  I'm hoping this can be fixed.  Thank you!

~Simon

**Comment by fetus-hina** [comment]
Please refer to #79

**Comment by SimonOrJ** [comment]
After some inspection, the latest commit 45e55dbc47ea186a0385c7b8c89428637d153ee3 is causing the error message to appear.

```json
Error from the flapg API:
{
  "error": "Nintendo Switch Online\u30a2\u30d7\u30ea\u306e\u66f4\u65b0\u306b\u3088\u308a\u30ed\u30b0\u30a4\u30f3\u3067\u304d\u307e\u305b\u3093"
}
```

**Comment by SimonOrJ** [comment]
I've updated the title accordingly

**Comment by frozenpandaman** [comment]
Re: your original question, `f` generation is broken due to the NSO app update. Please see the issue @fetus-hina linked.

---

Re: commit 45e55db, that actually should have caused the flapg API's error message to properly display the Japanese characters rather than non-ASCII escape sequences:
```
$ ./splatnet2statink.py 
splatnet2statink v1.4.3
Pulling data from online...
Blank cookie.
Attempting to generate new cookie...
Error from the flapg API:
{
  "error": "Nintendo Switch Onlineアプリの更新によりログインできません"
}
```

---

Re: the program exiting silently instead of printing an error message from the flapg API (your first comment & the new title of this issue), this seems to only happen when running the script using Python 2, because it can't handle the Japanese Unicode characters in the error message (lol). Still don't know how you got the escape codes to print out (your second comment) instead of it exiting silently, assuming you were still using Python 2, but oh well. :P

Anyway, I've now fixed that (forcing the flapg API output to be Unicode – this is the default in Python 3, but needs to be made explicit in Python 2) in e386d27, but it doesn't really matter because…

---

…I've taken the splatnet2statink API down for the time being to explain why `f` generation is broken (…again…) and that, in the meantime, people should follow the [mitmproxy instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) to obtain + input their cookie manually:

```
$ ./splatnet2statink.py 
splatnet2statink v1.4.3
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Error from the splatnet2statink API:
{
  "error": "The s2s API is temporarily offline as f generation has changed in the recent update to the Nintendo Switch Online app. For now, please follow the instructions here to obtain your iksm_session cookie: https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions"
}
```

**Comment by SimonOrJ** [comment]
> Still don't know how you got the escape codes to print out (your second comment) instead of it exiting silently, assuming you were still using Python 2, but oh well. :P

I used `git reset HEAD^ --hard` and tried it out and got that result on python.  I originally used it with `python2.7`, not knowing it should be run on python 3. /shrug

Thank you so much for detailed explanation, @frozenpandaman! You're the best :)
~Simon

**Comment by frozenpandaman** [comment]
Ahh interesting. Thanks!

>I originally used it with `python2.7`, not knowing it should be run on python 3.

We aim for compatibility with both! But Python 3 is preferred. ;)

I've also now updated the readme & docs to help out users who may be confused while automatic cookie generation is down.
