### ISSUE TITLE
Finalfest Shifty Station data isn't getting sent to stat.ink properly

### ISSUE THREAD

**Issue by Wolfy76700** [frozenpandaman/splatnet2statink#87]
The stage just displays as "Unknown" on [my Stat.ink profile](https://stat.ink/@MathiasWolfbrok/spl2)

**Comment by frozenpandaman** [comment]
Wow, so they *did* update the stages API at the last minute to include all the different variants… (cool!!!)

I can look into + fix this soon! Sorry for the trouble.

You should be able to manually edit the battles on stat.ink to display the correct stage since @fetus-hina has already added that functionality to the site. :)

**Comment by Wolfy76700** [comment]
Yeah, I did notice all of my previous Splatfest battle data was upgraded :-) Thanks!

**Comment by frozenpandaman** [comment]
Yup!

>@fetus-hina says: [14:29]
>Good news: We have raw JSON data if users use splatnet2statink. So I can update their data after all present. :muscle:

**Comment by fetus-hina** [comment]
@Wolfy76700 
Sorry for inconvenience. 
Please wait a while about past battles. I'll update data after exists 23 stages appeared.

FYI:
About the battles to be performed: If filled the "SplatNet 2" column of [this page](https://stat.ink/api-info/stage2), the stage of the battle will be recorded correctly. Otherwise (if empty), they will be updated later, unfortunately.

**Comment by frozenpandaman** [comment]
they should be looking correct on the stat.ink side now! (because hina updated stat.ink & s2s sends stage IDs in [`#key` format](https://github.com/frozenpandaman/splatnet2statink/blob/c738caff22c97896d324e53a492e15b5e00ab0b6/splatnet2statink.py#L824-L828))

started adding the known IDs in c738caf, too
