### ISSUE TITLE
splatnet2statink v1.5.3's cookie regeneration returns an upgrade error

### ISSUE THREAD

**Issue by InternalLoss** [frozenpandaman/splatnet2statink#91]
It seems Nintendo has updated their app again (iirc in time for Animal Crossing: New Horizon's new features) - trying to regenerate the stored cookie returns:
```
splatnet2statink v1.5.3
The stored cookie has expired.
Attempting to generate new cookie...
Error from Nintendo (in Account/Login step):
{
  "errorMessage": "Upgrade required.",
  "status": 9427,
  "correlationId": "REDACTED"
}
```

**Comment by frozenpandaman** [comment]
Thanks for the heads up! I noticed the app icon updated recently as well.

I'm traveling (on a train right now, going on 27 hours!) so can't check myself – @InternalLoss, could you try changing all instances of "`1.5.2`" in your local copy of [iksm.py](https://github.com/frozenpandaman/splatnet2statink/blob/master/iksm.py) to say "`1.6.1`" instead, run the script again, and see if that fixes/changes things? If so I can go ahead and make that fix.

**Comment by tkgstrator** [comment]
In my research, splatnet2statink failed to get splatoon access token at the point `https://api-lp1.znc.srv.nintendo.net/v1/Account/Login` then, Nintendo Server response `Invalid Token`. 

Conclusion, we may update not only 'User-Agent' but also s2s or flapg API.

```python
'User-Agent':      'OnlineLounge/1.6.1.2 NASDKAPI Android',
'X-ProductVersion': '1.6.1.2',
```

**Comment by InternalLoss** [comment]
Yeah, simply trying to update to 1.6.1.2 results in simply
```
{
  "error": "Too many requests"
}
```

**Comment by Jasper128** [comment]
getting this error since tonight:

`PS C:\Users\User\splatnet2statink> python splatnet2statink.py -r
splatnet2statink v1.5.3
The stored cookie has expired.
Attempting to generate new cookie...
Error(s) from Nintendo:
{
  "access_token": "_[long string of numbers and letters, removed it in case it's sensitive login info]_",
  "id_token": _[long string of numbers and letters, removed it in case it's sensitive login info]_,
  "expires_in": 900,
  "token_type": "Bearer",
  "scope": [
    "openid",
    "user",
    "user.birthday",
    "user.mii",
    "user.screenName"
  ]
}
{
  "clientFriendsOptedIn": true,
  "emailOptedInUpdatedAt": 1504979850,
  "updatedAt": 1567006471,
  "clientFriendsOptedInUpdatedAt": 1504979850,
  "gender": "male",
  "timezone": {
    "utcOffset": "+01:00",
    "utcOffsetSeconds": 3600,
    "id": "Europe/Berlin",
    "name": "Europe/Berlin"
  },
  "id": "bb1fd94e6d47f31f",
  "createdAt": 1504979850,
  "mii": {
    "storeData": {
      "3": "_[long string of numbers and letters, removed it in case it's sensitive login info]_"
    },
    "imageOrigin": "cdn-mii.accounts.nintendo.com",
    "imageUriTemplate": "https://{imageOrigin}/2.0.0/mii_images{/id}{/etag}.{format}{?type,expression,width,bgColor,clot
hesColor,cameraXRotate,cameraYRotate,cameraZRotate,characterXRotate,characterYRotate,characterZRotate,lightXDirection,li
ghtYDirection,lightZDirection,lightDirectionMode,splitDepthOffset,splitMode,instanceCount,instanceRotationMode}",
    "favoriteColor": "black",
    "clientId": "860a64b66b7e26c3",
    "etag": "c5c1f093eeb538d8550d42475317effc61964035",
    "coreData": {
      "4": "PEDFCAgHEwcPGwhsTwBobaFowhQIG7UgA7ZFQAYmQgC5A7EDYwC6A1AAsQPJAwYm"
    },
    "updatedAt": 1526397884,
    "type": "profile",
    "id": "072927db73a707f7"
  },
  "analyticsOptedIn": true,
  "eachEmailOptedIn": {
    "deals": {
      "optedIn": true,
      "updatedAt": 1504979850
    },
    "survey": {
      "optedIn": true,
      "updatedAt": 1504979850
    }
  },
  "screenName": "sp\u2022\u2022\u2022@g\u2022\u2022\u2022\u2022",
  "candidateMiis": [],
  "birthday": "1995-09-15",
  "nickname": "\u2606B\u03b9\u03b1c\u03baP\u03b1\u03c9\u2606",
  "isChild": false,
  "emailOptedIn": true,
  "language": "en-GB",
  "analyticsOptedInUpdatedAt": 1564941520,
  "country": "DE",
  "region": null,
  "emailVerified": true,
  "analyticsPermissions": {
    "internalAnalysis": {
      "permitted": true,
      "updatedAt": 1564941520
    },
    "targetMarketing": {
      "permitted": true,
      "updatedAt": 1564941520
    }
  }
}
PS C:\Users\User\splatnet2statink>`
