### ISSUE TITLE
Error from flapg API

### ISSUE THREAD

**Issue by ZweiSpeedruns** [frozenpandaman/splatnet2statink#95]
![image](https://user-images.githubusercontent.com/18094080/78326952-4211ac80-7541-11ea-9bbb-98a75d7e2976.png)
```
splatnet2statink v1.5.4
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Error from the flapg API: Error 404 (offline or incorrect headers).
```

**Comment by ariankordi** [comment]
I have also received this, I started getting this at least five hours ago.

If you actually visit the endpoint it's trying to reach, https://flapg.com/ika2/api/login?public, it will show a response body of
```json
{"error":"Nintendo Switch Onlineアプリの更新によりログインできません"}
```
, which will roughly translate to that the app needs to be updated. Since it's an Android server running, it will have to be done manually.

As implied in this issue comment by Eli: https://github.com/frozenpandaman/splatnet2statink/issues/86#issuecomment-508278767
NexusMine is the only one to fix the site/API. Inferring from his Twitter profile which is in Japanese and that the site returns text in Japanese, if he lives in Japan he should be on it shortly if he knows of it, as it shows that it's about 4 PM in Japan right now.

If the error could be improved on their part, 503 Service Temporarily Unavailable would be a more appropriate error to return, and this script could look for JSON and an error property, since that's what's being returned here.
I hope you find my insight useful.

**Comment by tkgstrator** [comment]
In my research, in case we call flapg API with 'x-ver: 3' parameter, the server responds 404 error. Moreover, previous update had changed that not using 'id_token' which is the one of responses of 'api/token' but it seems to be using again.

**Comment by frozenpandaman** [comment]
I've reached out to NexusMine for more info. :)

**Comment by frozenpandaman** [comment]
Just tried again and everything's working properly as-is now, guess it just went down for a bit. NexusMine shared a JS file with me as well to check against and we're doing everything properly. :)
