### ISSUE TITLE
1.5.4 session token fails to make cookie

### ISSUE THREAD

**Issue by InkxtheSquid** [frozenpandaman/splatnet2statink#98]
my session token expired recently and I was about to make a new one until somehow no cookie is being made at the moment, if this is happening a lot then I guess I should speak up about it

**Comment by InkxtheSquid** [comment]
Update: did a little debugging and I think the get_hash_from_s2s_api is screwy

**Comment by cgbuen** [comment]
flapg has been giving me a 404 whenever I've actually tried hitting the login endpoint over the last several days - @InkxtheSquid @frozenpandaman have you guys had any recent luck using this in the past week?

**Comment by frozenpandaman** [comment]
@cgbuen Just tried right now and it works for me.

**Comment by cgbuen** [comment]
@frozenpandaman I think I've figured out what's going on, at least for the node application I've been working on, and just wanted to get this out there somewhere (wasn't sure if it was worth opening a new GitHub Issue for).

flapg appears to have recently stopped accepting timestamps in milliseconds (the value given by `Date.now()` in JS). Dividing it down to seconds now yields me a response with a real, non-erroneous 200 OK response.

I discovered this when running splatnet2statink (which has already had time values in seconds, hence why s2s has seemed fine), seeing it successfully execute, logging the list of request headers for the flapg request, and comparing the difference in the values that my application was sending.

**Comment by frozenpandaman** [comment]
@cgbuen Hmm. The JS code that NexusMine passed me (so I could verify everything in iksm.py was correct) uses `"" + (new Date).getTime()` to generate the timestamp for the `x-time` header, which seems to return the same value/format as `Date.now()`.

**Comment by cgbuen** [comment]
Yeah, those two things do yield the same thing in JS, so that's a bit strange that that would be the means to verify.

I still contend that something new is happening here where seconds are preferred over milliseconds now - I just tried running splatnet2statink.py with the following:

  	timestamp = int(time.time()*1000)

And see it failing, whereas it works without the multiplier.

I've fiddling around with it a little more, I'm noticing that there's a date (some time around epoch 2147490304, which is January 19, 2038 9:05:04 PM PST, which is roughly 560149810 seconds from now) that seems like the threshold between a proper flapg response and a 404, lol.

**Comment by InkxtheSquid** [comment]
> Yeah, those two things do yield the same thing in JS, so that's a bit strange that that would be the means to verify.
> 
> I still contend that something new is happening here where seconds are preferred over milliseconds now - I just tried running splatnet2statink.py with the following:
> 
> ```
> timestamp = int(time.time()*1000)
> ```
> 
> And see it failing, whereas it works without the multiplier.
> 
> I've fiddling around with it a little more, I'm noticing that there's a date (some time around epoch 2147490304, which is January 19, 2038 9:05:04 PM PST, which is roughly 560149810 seconds from now) that seems like the threshold between a proper flapg response and a 404, lol.

I have a gut feeling that flapg does blocking, cuz if the code is working for others then what's the deal of those who fail with it?

**Comment by frozenpandaman** [comment]
>what's the deal of those who fail with it?

>I run a discord bot that uses splatnet2statink for retrieving cookies every minute

Yeah, maybe, uh, don't spam both of our servers  every minute? Sorry to be blunt, but what led you to thinking that was OK in any way? And why in god's name was this the default? Did you not read the usage guidelines? What led you to wanting a cookie every minute? I just blocked an IP on the domain level that had been spamming my site for the past week, which is by no stretch of the definition abusive behavior, and made it impossible to generate tokens for anyone else (#99).

**Comment by InkxtheSquid** [comment]
my deepest apologies thanks for letting me know what was going on I should've known sooner at this rate...

**Comment by frozenpandaman** [comment]
@InkxtheSquid In looking at [your bot](https://github.com/InkxtheSquid/Inkxbot), if all you need is generally-available schedule (map rotation) info, or stuff from Annie's Shop – i.e. not player-specific battle statistics and records – please use the splatoon2.ink API instead. It's also a ton simpler to use and doesn't require you generating user cookies, naturally. This is mentioned in the s2s API docs as well.

https://github.com/misenhower/splatoon2.ink/wiki/Data-access-policy

**Comment by InkxtheSquid** [comment]
@frozenpandaman I tried it once before but one time it couldn't retrieve anything from it for some reason I even contacted the dev of splatoon2.ink and he said everything was fine but I was still having problems

**Comment by frozenpandaman** [comment]
@InkxtheSquid What error did you run into? I recommend people use it because it makes life a lot easier, yours included... If you need help troubleshooting I can maybe try and help, but please do work on using that instead of this, per recommendation, and following the usage guidelines.

Also, the s2s API doesn't give "dedicated access" to Nintendo servers, it's just able to help you generate tokens to access user info (which you actually don't need here).

Instead of having your bot use my script to generate new cookies every 10 hours, why not just have it only do that _when_ and _only after_ they expire? They can last longer than 10 hours, after all.

>I don't really have to credit anything either

You're [plugging into](https://github.com/InkxtheSquid/Inkxbot/blob/rewrite/cogs/BackgroundtaskCog.py#L30) splatnet2statink, this project, directly, and I'd appreciate you crediting me, since it's a requirement for your bot to work...
