### ISSUE TITLE
splatnet2statink API is overloaded

### ISSUE THREAD

**Issue by ofiala-a51** [frozenpandaman/splatnet2statink#99]
When I need to generate new cookie, most of the time I just get "Too many requests error" from the splatnet2statink API that generates them. Guess that's not the way it should be, that's why I'm reporting it.

```
splatnet2statink v1.5.4
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Error from the splatnet2statink API:
{
  "error": "Too many requests"
}
```

**Comment by frozenpandaman** [comment]
From the API docs:

>The splatnet2statink API uses a token bucket system to control traffic. Requests to the API are globally limited to four per minute. If you receive an error, please wait ~30 seconds before trying again.

Can you confirm this is still happening after waiting a bit? I'll check out the server logs later, when I can, to see if anything looks odd.

**Comment by ofiala-a51** [comment]
Aha, I see. It works after waiting a bit, sure, I just thought maybe the limit should be higher, since I get that error almost every time I need to regenerate the cookie..?

**Comment by frozenpandaman** [comment]
It was just increased 2x following the changed in a971a21 – I would have guessed usage was higher over the past couple days due to the Splatfest but looking at the [stat.ink daily reports](http://elifessler.com/s2s/), it doesn't seem to be, huh.

Anyway, oof – got around to checking the logs and there are two IPs constantly spamming requests over and over (probably someone's autorun script gone haywire)… one almost constantly since April 14th of the. (I should probably write some sort of monitor to detect these sort of things…) They're now blocked at domain-level so the server isn't being inundated with requests, and you should be able to generate tokens a lot easier. :) Thanks @ofiala-a51!
